name: icpr2020
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - av=6.2.0
  - albumentations
  - cudatoolkit
  - ffmpeg
  - jupyter
  - numpy
  - opencv=3.4.2
  - py-opencv=3.4.2
  - python=3.6.9
  - pip
  - pytorch=1.4.0
  - torchvision
  - tqdm
  - pandas
  - pip:
    - tensorboardx==2.0
    - efficientnet-pytorch
    - scikit-learn

