name: icpr2020
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py36_0
  - av=6.2.0=py36ha5cc088_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h2e261b9_0
  - cloudpickle=1.2.2=py_0
  - cryptography=2.8=py36h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask-core=2.9.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - docutils=0.15.2=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - fsspec=0.6.2=py_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.13=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - ignite=0.2.1=py36_0
  - imageio=2.6.1=py36_0
  - intel-openmp=2019.4=243
  - ipython=7.10.2=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.15.1=py36_0
  - jmespath=0.9.4=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.15=h516909a_1005
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py36_0
  - matplotlib=3.1.1=py36h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.3=0
  - networkx=2.4=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.17.4=py36hc1035e2_0
  - numpy-base=1.17.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1d=h7b6447c_3
  - pandas=1.0.0=py36h0573a6f_0
  - parso=0.5.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.2.1=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pycparser=2.19=py36_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.7.1=py36_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.1=py_0
  - pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - s3fs=0.4.0=py_0
  - scikit-image=0.15.0=py36he6710b0_0
  - scikit-learn=0.21.3=py36hd81dba3_0
  - scipy=1.4.1=py36h0b6359f_0
  - setuptools=42.0.2=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.13.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py36_cu101
  - tornado=6.0.3=py36h7b6447c_0
  - tqdm=4.40.0=py_0
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.7=py36_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - tensorboard==2.1.0
    - tensorboardx==2.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - tensorflow-gpu==2.0.0
    - tensorflow-tensorboard==1.5.1
    - efficientnet-pytorch

